### ISSUE TITLE
Incorrect stack trace shown

### ISSUE THREAD

**Issue by jesseduffield** [ghilesmeddour/faktory_worker_python#8]
Thanks for making this package.

Currently, when I raise an issue from within my task, the stack trace only shows this package's code:

![image](https://github.com/ghilesmeddour/faktory_worker_python/assets/8456633/f72c7228-bff2-4043-9547-3acb0661d1f4)

This is with the following task:
```py
def adder(x, y):
    if x > 50:
        raise(ValueError("a is greater than 50"))
```

I would expect the stack trace to involve my own code

**Comment by ghilesmeddour** [comment]
Hi @jesseduffield,

You can set "backtrace" [field](https://github.com/contribsys/faktory/blob/main/docs/protocol-specification.md#optional-fields) to the number of lines you want to keep ([default is 5](https://github.com/ghilesmeddour/faktory_worker_python/blob/639b3e663f4e086d3fb091a5ebb4c3cc29f8e247/src/pyfaktory/models.py#L18)).

Example:
`job_1 = Job(jobtype='foo', backtrace=10)`

**Comment by jesseduffield** [comment]
That's interesting: whether I set that value or not, I'm still only seeing the same three lines as in the above screenshot.

It seems like there's two issues at play:
1) the original exception is excluded
2) newlines in the stack trace aren't being split on

debug log output:

```
 06:25:12 - FaktoryConsumer - WARNING - Task (job 5094c6d188b14bb19d04a4a953ded426) raised <class 'ValueError'>: a is greater than 70
 06:25:12 - FaktoryClient - DEBUG - C: FETCH default

 --- Logging error ---
 pebble.common.RemoteTraceback: Traceback (most recent call last):
   File "/app/venv/lib/python3.11/site-packages/pebble/common.py", line 175, in process_execute
     return Result(SUCCESS, function(*args, **kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/app/core/tasks/adder.py", line 11, in adder
     raise(ValueError("a is greater than 70"))
 ValueError: a is greater than 70


 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/app/venv/lib/python3.11/site-packages/pyfaktory/consumer.py", line 139, in task_done
     result = future.result()
              ^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
     return self.__get_result()
            ^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
     raise self._exception
 ValueError: a is greater than 70

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
     msg = self.format(record)
           ^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
     return fmt.format(record)
            ^^^^^^^^^^^^^^^^^^
   File "/app/venv/lib/python3.11/site-packages/coloredlogs/__init__.py", line 1140, in format
     return logging.Formatter.format(self, record)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
     record.message = record.getMessage()
                      ^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
     msg = msg % self.args
           ~~~~^~~~~~~~~~~
 TypeError: not all arguments converted during string formatting
 Call stack:
   File "/usr/local/lib/python3.11/threading.py", line 995, in _bootstrap
     self._bootstrap_inner()
   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
     self.run()
   File "/usr/local/lib/python3.11/threading.py", line 975, in run
     self._target(*self._args, **self._kwargs)
   File "/app/venv/lib/python3.11/site-packages/pebble/pool/process.py", line 192, in message_manager_loop
     pool_manager.process_next_message(SLEEP_UNIT)
   File "/app/venv/lib/python3.11/site-packages/pebble/pool/process.py", line 229, in process_next_message
     self.task_manager.task_done(message.task, message.result)
   File "/app/venv/lib/python3.11/site-packages/pebble/pool/process.py", line 310, in task_done
     task.future.set_exception(result.value)
   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 565, in set_exception
     self._invoke_callbacks()
   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
     callback(self)
   File "/app/venv/lib/python3.11/site-packages/pyfaktory/consumer.py", line 152, in task_done
     self.logger.debug(
 Message: 'Task (job 5094c6d188b14bb19d04a4a953ded426) backtrace: '
 Arguments: (['  File "/app/venv/lib/python3.11/site-packages/pyfaktory/consumer.py", line 139, in task_done\n    result = future.result()\n             ^^^^^^^^^^^^^^^\n', '  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result\n    return self.__get_result()\n
```

In the above output, the part that really matters to me is:

```
   File "/app/core/tasks/adder.py", line 11, in adder
     raise(ValueError("a is greater than 70"))
 ValueError: a is greater than 70
```

But that does not appear.

Looks like one of the issues is:

```py
            self.logger.debug(
                f"Task (job {future.job_id}) backtrace: ",
                traceback.format_tb(err_traceback),
            )
```

which should be:
```py
            self.logger.debug(
                f"Task (job {future.job_id}) backtrace: {traceback.format_tb(err_traceback)}",
            )
```

This is the cause of the exception 'TypeError: not all arguments converted during string formatting'.

As for the newlines, that appears to be the default behaviour of the traceback module, but given how sidekiq renders newlines (i.e. just converts them to spaces), I would split the array based on those newlines (which would mean that the default backtrace of 5 would indeed lead to 5 lines being shown in sidekiq, as opposed to the current 3)

**Comment by ghilesmeddour** [comment]
Thanks @jesseduffield for the description of the problem. I can see now. Would you be willing to investigate and make a PR to fix it?
